### ISSUE TITLE
Missing file to run examples

### ISSUE THREAD

**Issue by Samsy** [spite/Wagner#11]
For minefield example : 

GET http://127.0.0.1:8888/Wagner/Wagner.experimental.js 

undefined: 
      controls = new THREE.OrbitControls( camera );

I didnt check all examples, but i suppose there are others missing files too !

**Comment by spite** [comment]
Forgot to push the changes after adding OrbitControls to the examples https://github.com/spite/Wagner/commit/936fc7fc4dd5817901c206030276836686bbe457

**Comment by Samsy** [comment]
Sorry Spite, 
It miss that file too 

fragment-shaders/halftone-cmyk-fs.glsl

for the halftone-cmyk example !

Very nice tool !

**Comment by spite** [comment]
Not all examples have working passes. Some are broken (like ToonPass, some
are incomplete, like some SSAO implementations or that CMYK Halftone).
That's why it's called a minefield, sorry!
