### ISSUE TITLE
Chrome locks up

### ISSUE THREAD

**Issue by willy-vvu** [spite/Wagner#2]
I'm a big fan of Wagner! It's very impressive, and easy to use.

I visited the demo at www.clicktorelease.com/tmp/wagner/ and that works perfectly.
However, the current version of index.html in the repo (of commit 2ee57a) freezes up Chrome and crashes my GPU when I serve it locally in Chrome.
I suspect it's a problem with ANGLE that was inadvertently caused by changes from the previous version to the current one.
I was hoping to use Wagner for my next project. Help is much appreciated!

OS: Windows 8.1 64 bit
GPU: Geforce GTX 750M
Chrome: 33.0.1750.154 m

**Comment by spite** [comment]
Should be fixed for Windows/ANGLE, iOS and Android.
