### ISSUE TITLE
Can't get Wagner to work with R73

### ISSUE THREAD

**Issue by amorino** [spite/Wagner#23]
I get the following warnings and error: 

>WebGL: INVALID_VALUE: shaderSource: string not ASCII

>THREE.WebGLShader: Shader couldn't compile.

>THREE.WebGLProgram: shader error:  1281 gl.VALIDATE_STATUS false gl.getProgramInfoLog invalid shaders  ERROR: 0:? : '' : syntax error

**Comment by spite** [comment]
I would need a bit more info. What system are you using; are you using some of the examples or your own code?
