### ISSUE TITLE
Sampler Arrays indexed with non-constant expresions are forbidden (GLSL > 1.30)

### ISSUE THREAD

**Issue by cookiengineer** [spite/Wagner#26]
The above error is triggered by the shader compiler in an up-to-date Chrome (Version 48.0.2564.116).

Of course, all the dependent getAttribLocation / vertexAttribPointer etc. won't work then ... so there are a bunch of those errors afterwards.

**Error**

```
THREE.WebGLShader: gl.getShaderInfoLog() 0:110(57): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later
```

**Screenshot**

I uploaded a screenshot from your demo to [imgur](http://i.imgur.com/UtrDh1i.png) here.

Another suggestion I'd like to make is to have something like window.onblur = function() { stop_renderloop(); } - at least for the demo.

Crashing programs are pretty much impossible to debug while an endless loop of errors is still running.

**Comment by cookiengineer** [comment]
Well, shit. I found now a related bug in [three.js](https://github.com/mrdoob/three.js/issues/6115) where the outcome of the [Chromium Bug](https://bugs.chromium.org/p/chromium/issues/detail?id=550487) is that it will be fixed in Chrome 49 (but is broken in Chrome 46 to 48).

**Comment by spite** [comment]
Hi! So it's a bug that affects three.js?

**Comment by cookiengineer** [comment]
I guess so, it's somehow fixed in some three.js demos and not fixed in some others. So I guess it's maybe fixed in the latest three.js version!?

It didn't occur in some rev 6x demos, and it's seemingly fixed in [the renault demo](http://www.littleworkshop.fr/renaultespace/) that is using THREE.WebGLRenderer 71.

So I will try it with Chromium Beta and ping back here if it's really browser-related or dependent on the three.js version.

I'm kind of unsure whether three.js compiles false shaders or the browser is implementing the ANGLE layer in an error-prone way for Intel drivers.
