### ISSUE TITLE
what happened to Position and Velocity pass?

### ISSUE THREAD

**Issue by jaredmcqueen** [spite/Wagner#8]
I'm looking at this older example:
http://www.neveroccurs.com/lab/three.js/gpu_particles/index.html?particles=256

and see that they use two passes that aren't available:
WagnerPositionPass.js
WagnerVelocityPass.js

I was wondering why they got dropped, or if they still exist but are called something else?

I'm working on a project that has tens of thousands of particles and I need to animate them using vertex shaders -- would using wagner be a viable solution?

**Comment by spite** [comment]
Hi, they didn't get dropped, those were done by @fazeaction as an experiment. There's an ongoing development to add generic simulation passes to Wagner.

Even though this answer probably comes very late for your project, yes, you can use Wagner as an FBO/DataTexture manager to run simulations on the GPU.
