### ISSUE TITLE
[question] depth map and transparent objects

### ISSUE THREAD

**Issue by makc** [spite/Wagner#9]
Actually, I have two questions,
1 where do you discuss this thing, any ML, irc channel, skype chat? issues are not really proper tool; and
2 does this thing handle transparent objects with e.g. dof? Recently [I had to fight with three.js in order to get it working](https://makc3d.wordpress.com/2015/01/13/three-js-dof-and-transparency/), but would prefer some ootb solution.

**Comment by makc** [comment]
I looked at the code, and it seems you just calculate depth per vertex and output interpolated depth in fragment shader. Which requires similar hacks as vanilla 3js to work with transparent stuff.

Closing then.

**Comment by spite** [comment]
Hi!

There isn't a proper discussion channel  really. So far it's been over e-mail or GitHub.

Regarding transparency: good question. There isn't a clean-cut solution, of course. What you've been working on covers it pretty much.

Common depth materials render all depth of the object, without taking into consideration the actual alpha map of the object, or its opacity. Opacity is tricky to solve when using a depth buffer, but binary alpha can be used, it's just a matter of modifying the depth material shader so it uses the alpha channel to discard fragments when they're transparent.
